### PR TITLE
Added a API Key area... Not complete

### PR DESCRIPTION
**Pull request by QuartzWarrior**
Couldn't find where the api key goes... so I left that to you on line 54

### CODE REVIEW

**Comment by QuartzWarrior** [comment]
I added this in case someone would rather use their existing API key instead of handing over their login info.

**Comment by mathsman5133** [comment]
Hi, this is currently implemented in v2 with `login_with_keys`. 

v2 still requires a bit more testing, but if you want to use it in the meantime you can `pip install -U git+https://github.com/mathsman5133/coc.py@v2`.

Thanks anyways.

**Comment by QuartzWarrior** [comment]
> Hi, this is currently implemented in v2 with `coc.login_with_keys`.
> 
> v2 still requires a bit more testing, but if you want to use it in the meantime you can `pip install -U git+https://github.com/mathsman5133/coc.py@v2`.
> 
> Thanks anyways.

Is there documentation for v2 somewhere? np

**Comment by mathsman5133** [comment]
v2 docs: https://cocpy.readthedocs.io/en/v2/index.html

login_with_keys: https://cocpy.readthedocs.io/en/v2/code_overview/client.html#coc.login_with_keys

**Pull request closed without merging**
