### PR TITLE
Fixed bug in keys deletion

### PR DESCRIPTION
**Pull request by AumJavalgikar**
Deleting elements from a list as we loop over it is problematic, let's instead loop over a copy of keys instead, also fixed a minor typo

### CODE REVIEW

**Comment by doluk** [comment]
Can you please check which branch you are using as base? there are way more changes in this pr than you described

**Comment by AumJavalgikar** [comment]
I was trying to update my repo to match g8_2.4.0_cadidate which created the extra changes, if you check the last commit in the PR you will see what I'm trying to do

**Comment by doluk** [comment]
Create a branch based of the master branch in this repo and then make the pr from that. You are just adding commits with content we already have

**Comment by AumJavalgikar** [comment]
okay, give me a minute to figure this out

**Comment by doluk** [comment]
I agree on the change. I can do it directly without the pr as long as you dont want the pr merged for your stats :D
As you prefer

**Pull request closed without merging**
