### PR TITLE
solving calendar.IllegalMonthError:

### PR DESCRIPTION
**Pull request by av02**
solving a calender problem that made a 13nd month, and then an exception.

### CODE REVIEW

**Comment by doluk** [comment]
Good find!!
I think we can make it even better.
If I am not wrong, the if in line 357 will always be wrong, so we can remove that part and clean up the rest a bit. Init the month and year ifthey are none, then check for the new year problem while going to the next month and then call  get_season_start.

Thank you for the pull request!

**Comment by av02** [comment]
I think you're right.
thank you for your work!

**Comment by majordoobie** [comment]
Could you post a snippet of the error you were getting please

**Comment by majordoobie** [comment]
Doluk clued me in. Thank you for your hard work :)

**Pull request merged**
