### PR TITLE
Fix PyPi workflow to use newer `build` tool, and add back in checking out repo.

### PR DESCRIPTION
**Pull request by mathsman5133**
If someone knows how to make the check box a compulsory "true" for the workflow_dispatch that would be good, too, but I'm not too fussed

### CODE REVIEW

**Comment by lukasthaler** [comment]
Should be able to check steps.sptep_name.outputs.confirmation in a new step and just cancel the flow if it's not true

**Comment by lukasthaler** [comment]
Nvm, that's an input. Something like inputs.confirmation should be available to check in a step

**Comment by mathsman5133** [comment]
Yep, do you know how that works (if the field exists / is empty) if it's called from an event (on release)? I'll have a look tomorrow otherwise

**Comment by lukasthaler** [comment]
I should be able to do that, but idk if I can get to it today

**Comment by mathsman5133** [comment]
OK, did a quick test and this seems to be good (skips when input is false, runs when true)... bit hard to test the release option but it should be fine :)

**Review by lukasthaler — APPROVED** [review]
lgtm

**Pull request merged**
