### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by Kuchenmampfer**
Alright, since you are sooo fast now doobie, I will just make this PR right away

### CODE REVIEW

**Comment by majordoobie** [comment]
Could you please provide what was breaking and what code did you use to show that it was breaking.

**Comment by doluk** [comment]
the issue is this one https://stackoverflow.com/questions/3935675/python-reclaiming-memory-after-deleting-items-in-a-dictionary behind the scene.

**Comment by Kuchenmampfer** [comment]
The cache of my daemon always grew over time. To investigate it, I added daily memory usage logging to my daemon in this commit: https://codeberg.org/Kuchenmampfer/ClashNight/commit/e96e9a97ec0f6477653d1ca95fdf782d3d5110ec
In short, I just let tracemalloc take a snapshot of the memory usage each day and logged the changes. With this, I was able to figure out that I had 250k more instances of the `Route.url` string each day and started tracing its usage. I turned out that this string was used by the cache as a key. So the old `_cache_remove` funktion somehow did not result in the keys being picked up by the garbage collector. Magic discovered that this is what doluk just commented and could be fixed by copying the cache. But since copying it with every delete would create too much overhead, I figured that it would be a good idea to check `cache.max_size` and copy the cache once that is reached.

**Comment by Kuchenmampfer** [comment]
here is the output of tracemalloc after the second day of running:
```py
/home/discordbots/ClashNight/venv/lib/python3.9/site-packages/coc/http.py:168: size=48.1 MiB (+24.0 MiB), count=501531 (+250701), average=101 B
```

**Comment by Kuchenmampfer** [comment]
And with my fix and the default `cache.max_size`, it should grow to 1MB and be then reset to 0. Until this point, my logging does indeed not show significant memory usage caused by that `Route.url` string.

**Comment by Kuchenmampfer** [comment]
Alright. The issue of my solution was that `self.cache.copy` did not return an LRU object, but just a dict. So after a copy, the cache was a dict which misses important functionality of the LRU. I fixed this by implementing my own `LRU().copy()` function. But for this I had to change the inheritance `LRU(dict)` to `LRU(UserDict)`. UserDict is a python implementation of dict meant for inheritance. It does implement all the functionality of dict, but does not come with some inheritance issues caused by the fact that `dict` is implemented in c for performance reasons.

**Comment by Kuchenmampfer** [comment]
Details can be read in #162

**Pull request merged**
